TAG = latest
REPOSITORY = cs-ghost

build: config.js config.sh
	docker build -t "${REPOSITORY}:${LATEST}" .

config.js:
	@echo Please add config.js; false

config.sh:
	@echo Please add config.sh; false
